{{- if and .Values.mongodb.enabled .Values.mongodb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "swimlane-app.mongodb.serviceAccountName" . }}
  labels:
    {{- include "swimlane-app.mongodb.labels" . | nindent 4 }}
  {{- with .Values.mongodb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

